### ISSUE TITLE
Issue installing OpenBGPd-state server

### ISSUE THREAD

**Issue by moshivji** [alice-lg/openbgpd-state-server#1]
Hi when we follow the instructions we seem to get the following,

```
cron@wendy:/tmp$ go get github.com/alice-lg/openbgp-state-server/cmd/openbgpd-state-server
# cd .; git clone https://github.com/alice-lg/openbgp-state-server /home/linx-cron/go/src/github.com/alice-lg/openbgp-state-server
Cloning into '/home/linx-cron/go/src/github.com/alice-lg/openbgp-state-server'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/alice-lg/openbgp-state-server/cmd/openbgpd-state-server: exit status 128
```

We added a 'd' into the URL and also got the following, 

```
cron@wendy:/tmp$ go get github.com/alice-lg/openbgpd-state-server/cmd/openbgpd-state-server
# github.com/alice-lg/openbgpd-state-server/pkg/server
/home/linx-cron/go/src/github.com/alice-lg/openbgpd-state-server/pkg/server/state_server.go:89:12: undefined: strings.ReplaceAll
/home/linx-cron/go/src/github.com/alice-lg/openbgpd-state-server/pkg/server/state_server.go:122:5: undefined: errors.Is
```

Any ideas what be causing this not to install correctly ?

Does OpenBGPd-state-server require Go higher then 1.10 ?

Kind Regards

Mo

**Comment by annikahannig** [comment]
I just checked: `errors.Is` was added in go1.13 and `strings.ReplaceAll` in 1.12.

**Comment by tonyvroon** [comment]
But the documentation states 1.10 is supported, please could that be updated?

**Comment by tonyvroon** [comment]
Thank you for updating the minimum version. Could you also update the "go get" URL that you advertise?
It is in the same document, and apparently "openbgp-state-server" is a private project that requires credentials.

**Comment by annikahannig** [comment]
Ah no there was just a small typo. No private repo.

**Comment by tonyvroon** [comment]
Thank you, I now see:
```
/tmp$ go get github.com/alice-lg/openbgpd-state-server/cmd/openbgpd-state-server
# github.com/alice-lg/openbgpd-state-server/cmd/openbgpd-state-server
/home/tony/go/src/github.com/alice-lg/openbgpd-state-server/cmd/openbgpd-state-server/main.go:52:2: undefined: flag.Func
/home/tony/go/src/github.com/alice-lg/openbgpd-state-server/cmd/openbgpd-state-server/main.go:53:2: undefined: flag.Func
/home/tony/go/src/github.com/alice-lg/openbgpd-state-server/cmd/openbgpd-state-server/main.go:54:2: undefined: flag.Func

/tmp$ go version
go version go1.13.8 linux/amd64

```

**Comment by tonyvroon** [comment]
Correct me if I'm wrong, but isn't that a Go 1.16 function? I am basing this on https://www.alexedwards.net/blog/custom-command-line-flags

**Comment by tonyvroon** [comment]
It will be very difficult to package this for our usage if the default Ubuntu 20.04 Go language version, 1.13, is not supported. (Our preference would be for 1.10 to support Ubuntu 18.04, but I realise that may be impractical)

**Comment by tonyvroon** [comment]
I have worked around our immediate issue locally; if you could update your README to state the minimum supported Go release is 1.16 then the issue is resolved. Thank you.

**Comment by annikahannig** [comment]
I updated the README :)
